export const ArtistsData = [
  {
    id: 1,
    artistName: "Trademark",
    artistImage: "ns1.jpg",
    introduce:"Trademark are an English band",
    numberOfFollower: "197.713",
  },
  {
    id: 2,
    artistName: "Band",
    numberOfFollower: "927.713",
    introduce:"The Band was a Canadian-American rock band formed in Toronto, Ontario",
    artistImage: "ns2.png",
  },
  {
    id: 3,
    artistName: "Cool",
    artistImage: "ns3.jpg",
    introdude:"Cool",
    numberOfFollower: "227.713",
  },
  {
    id: 4,
    artistName: "BTS",
    artistImage: "BTS_image.jpg",
    introduce:"BTS",
    numberOfFollower: "927.713",
  },
  {
    id: 5,
    artistName: "V",
    artistImage: "ns6.jpg",
    introduce:"V",
    numberOfFollower: "907.713",
  },
  {
    id: 6,
    artistName: "Jin",
    artistImage: "BTS_image.jpg",
    introduce:"Jin",
    numberOfFollower: "927.713",
  },
  {
    id: 7,
    artistName: "Nicki Minaj",
    artistImage: "BTS_image.jpg",
    introduce:"Nicki Minaj",
    numberOfFollower: "927.713",
  },
  {
    id: 8,
    artistName: "IU",
    artistImage: "ns1.jpg",
    introduce:"IU",
    numberOfFollower: "927.713",
  },
  {
    id: 9,
    artistName: "911",
    artistImage: "ns6.jpg",
    introduce:"911",
    numberOfFollower: "107.713",
  },
];
